### ISSUE TITLE
No favicon!!

### ISSUE THREAD

**Issue by engineerchange** [mrisdal/blog#2]
Great idea: [tweet](https://twitter.com/MeganRisdal/status/1100651168517173248); I may need to learn more about your "new hobbies" before I could suggest post ideas.

However, you should add a favicon to your blog page!

Cheers!

**Comment by mrisdal** [comment]
Totally--thank you! [Favicon added](https://github.com/mrisdal/blog/commit/dfe7d0f14da90060c2fba9e8f88b30ede914554e).
